# Generated by Django 3.1.4 on 2020-12-05 11:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='column',
            field=models.IntegerField(default=1, validators=[main.models.positive_integer]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='row',
            field=models.IntegerField(default=1, validators=[main.models.positive_integer]),
            preserve_default=False,
        ),
    ]
